### ISSUE TITLE
Allow Locale Definition for Translation

### ISSUE THREAD

**Issue by solverat** [w3r-one/json-schema-bundle#12]
Allow to determinate specific locale. In API context, we're requesting the same form with different locales - therefor, a dynamic definition would be useful.

We could use the [global lang attribute](https://developer.mozilla.org/en-US/docs/Web/HTML/Global_attributes/lang) in the form `attr` option, with a default of `null`, if not available.

https://github.com/w3r-one/json-schema-bundle/blob/14032af815af6a422619b698dfe2cee68a1a275f/src/Transformer/AbstractTransformer.php#L144-L152

**Comment by laurent-bientz** [comment]
hey @solverat to be sure to fully understand, you don't have any localized routes in your API ? because if yes, in theory request.locale is set with the correct locale and you've nothing to do, the translator will use the current locale extracted from the request.

**Comment by solverat** [comment]
Yes, but in our case, the request locale is not always bounded to the form API request (comes from a different header attribute). In my proposal, I would return `null` if the `lang` attribute is not available (which then would fall back to your described default behavior).

**Comment by laurent-bientz** [comment]
ping @solverat

**Comment by solverat** [comment]
Hey @laurent-bientz, had a busy time - sorry for the late response! :)

The corresponding PR looks good to me, thank you very much for your efforts!

**Comment by laurent-bientz** [comment]
Hey @solverat, pull request has been merged and released into https://github.com/w3r-one/json-schema-bundle/releases/tag/1.2.0
